platform :ios, '<%= deployment_target %>'
source 'https://github.com/CocoaPods/Specs'

# Uncomment this line if you use Swift
use_frameworks!

def pods
    pod 'Typhoon', '~> 3.4'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'AFNetworking', '~> 3.0'
    pod 'Groot', '~> 1.2'
    pod 'Fabric'
    pod 'Crashlytics'  
end

target '<%= project_name %>' do
    pods
end

target '<%= test_target_name %>' do
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'OCMockito', '~> 3.0'
    pod 'AFNetworking', '~> 3.0'
end